# JAMPVITA source sets - mechanically extracted from the vendored codemp CMake lists.

set(JAMP_ENGINE_SOURCES
    src/codemp/botlib/be_aas_bspq3.cpp
    src/codemp/botlib/be_aas_cluster.cpp
    src/codemp/botlib/be_aas_debug.cpp
    src/codemp/botlib/be_aas_entity.cpp
    src/codemp/botlib/be_aas_file.cpp
    src/codemp/botlib/be_aas_main.cpp
    src/codemp/botlib/be_aas_move.cpp
    src/codemp/botlib/be_aas_optimize.cpp
    src/codemp/botlib/be_aas_reach.cpp
    src/codemp/botlib/be_aas_route.cpp
    src/codemp/botlib/be_aas_routealt.cpp
    src/codemp/botlib/be_aas_sample.cpp
    src/codemp/botlib/be_ai_char.cpp
    src/codemp/botlib/be_ai_chat.cpp
    src/codemp/botlib/be_ai_gen.cpp
    src/codemp/botlib/be_ai_goal.cpp
    src/codemp/botlib/be_ai_move.cpp
    src/codemp/botlib/be_ai_weap.cpp
    src/codemp/botlib/be_ai_weight.cpp
    src/codemp/botlib/be_ea.cpp
    src/codemp/botlib/be_interface.cpp
    src/codemp/botlib/l_crc.cpp
    src/codemp/botlib/l_libvar.cpp
    src/codemp/botlib/l_log.cpp
    src/codemp/botlib/l_memory.cpp
    src/codemp/botlib/l_precomp.cpp
    src/codemp/botlib/l_script.cpp
    src/codemp/botlib/l_struct.cpp
    src/codemp/client/FXExport.cpp
    src/codemp/client/FxPrimitives.cpp
    src/codemp/client/FxScheduler.cpp
    src/codemp/client/FxSystem.cpp
    src/codemp/client/FxTemplate.cpp
    src/codemp/client/FxUtil.cpp
    src/codemp/client/cl_avi.cpp
    src/codemp/client/cl_cgame.cpp
    src/codemp/client/cl_cgameapi.cpp
    src/codemp/client/cl_cin.cpp
    src/codemp/client/cl_console.cpp
    src/codemp/client/cl_input.cpp
    src/codemp/client/cl_keys.cpp
    src/codemp/client/cl_lan.cpp
    src/codemp/client/cl_main.cpp
    src/codemp/client/cl_net_chan.cpp
    src/codemp/client/cl_parse.cpp
    src/codemp/client/cl_scrn.cpp
    src/codemp/client/cl_ui.cpp
    src/codemp/client/cl_uiapi.cpp
    src/codemp/client/snd_ambient.cpp
    src/codemp/client/snd_dma.cpp
    src/codemp/client/snd_mem.cpp
    src/codemp/client/snd_mix.cpp
    src/codemp/client/snd_mp3.cpp
    src/codemp/client/snd_music.cpp
    src/codemp/ghoul2/G2_gore.cpp
    src/codemp/icarus/BlockStream.cpp
    src/codemp/icarus/GameInterface.cpp
    src/codemp/icarus/Instance.cpp
    src/codemp/icarus/Interface.cpp
    src/codemp/icarus/Memory.cpp
    src/codemp/icarus/Q3_Interface.cpp
    src/codemp/icarus/Q3_Registers.cpp
    src/codemp/icarus/Sequence.cpp
    src/codemp/icarus/Sequencer.cpp
    src/codemp/icarus/TaskManager.cpp
    src/codemp/mp3code/cdct.c
    src/codemp/mp3code/csbt.c
    src/codemp/mp3code/csbtb.c
    src/codemp/mp3code/csbtl3.c
    src/codemp/mp3code/cup.c
    src/codemp/mp3code/cupini.c
    src/codemp/mp3code/cupl1.c
    src/codemp/mp3code/cupl3.c
    src/codemp/mp3code/cwin.c
    src/codemp/mp3code/cwinb.c
    src/codemp/mp3code/cwinm.c
    src/codemp/mp3code/hwin.c
    src/codemp/mp3code/l3dq.c
    src/codemp/mp3code/l3init.c
    src/codemp/mp3code/mdct.c
    src/codemp/mp3code/mhead.c
    src/codemp/mp3code/msis.c
    src/codemp/mp3code/towave.c
    src/codemp/mp3code/uph.c
    src/codemp/mp3code/upsf.c
    src/codemp/mp3code/wavep.c
    src/codemp/qcommon/GenericParser2.cpp
    src/codemp/qcommon/RoffSystem.cpp
    src/codemp/qcommon/cm_load.cpp
    src/codemp/qcommon/cm_patch.cpp
    src/codemp/qcommon/cm_polylib.cpp
    src/codemp/qcommon/cm_test.cpp
    src/codemp/qcommon/cm_trace.cpp
    src/codemp/qcommon/cmd.cpp
    src/codemp/qcommon/common.cpp
    src/codemp/qcommon/cvar.cpp
    src/codemp/qcommon/files.cpp
    src/codemp/qcommon/huffman.cpp
    src/codemp/qcommon/matcomp.cpp
    src/codemp/qcommon/md4.cpp
    src/codemp/qcommon/md5.cpp
    src/codemp/qcommon/msg.cpp
    src/codemp/qcommon/net_chan.cpp
    src/codemp/qcommon/net_ip.cpp
    src/codemp/qcommon/persistence.cpp
    src/codemp/qcommon/q_shared.cpp
    src/codemp/qcommon/stringed_ingame.cpp
    src/codemp/qcommon/stringed_interface.cpp
    src/codemp/qcommon/vm.cpp
    src/codemp/qcommon/z_memman_pc.cpp
    src/codemp/rd-common/tr_font.cpp
    src/codemp/rd-common/tr_image_jpg.cpp
    src/codemp/rd-common/tr_image_load.cpp
    src/codemp/rd-common/tr_image_png.cpp
    src/codemp/rd-common/tr_image_tga.cpp
    src/codemp/rd-common/tr_noise.cpp
    src/codemp/rd-vanilla/G2_API.cpp
    src/codemp/rd-vanilla/G2_bolts.cpp
    src/codemp/rd-vanilla/G2_bones.cpp
    src/codemp/rd-vanilla/G2_misc.cpp
    src/codemp/rd-vanilla/G2_surfaces.cpp
    src/codemp/rd-vanilla/tr_WorldEffects.cpp
    src/codemp/rd-vanilla/tr_arb.cpp
    src/codemp/rd-vanilla/gl_vita_ext.cpp
    src/codemp/rd-vanilla/tr_backend.cpp
    src/codemp/rd-vanilla/tr_bsp.cpp
    src/codemp/rd-vanilla/tr_cmds.cpp
    src/codemp/rd-vanilla/tr_curve.cpp
    src/codemp/rd-vanilla/tr_decals.cpp
    src/codemp/rd-vanilla/tr_ghoul2.cpp
    src/codemp/rd-vanilla/tr_image.cpp
    src/codemp/rd-vanilla/tr_init.cpp
    src/codemp/rd-vanilla/tr_light.cpp
    src/codemp/rd-vanilla/tr_main.cpp
    src/codemp/rd-vanilla/tr_marks.cpp
    src/codemp/rd-vanilla/tr_mesh.cpp
    src/codemp/rd-vanilla/tr_model.cpp
    src/codemp/rd-vanilla/tr_quicksprite.cpp
    src/codemp/rd-vanilla/tr_scene.cpp
    src/codemp/rd-vanilla/tr_shade.cpp
    src/codemp/rd-vanilla/tr_shade_calc.cpp
    src/codemp/rd-vanilla/tr_shader.cpp
    src/codemp/rd-vanilla/tr_shadows.cpp
    src/codemp/rd-vanilla/tr_skin.cpp
    src/codemp/rd-vanilla/tr_sky.cpp
    src/codemp/rd-vanilla/tr_surface.cpp
    src/codemp/rd-vanilla/tr_surfacesprites.cpp
    src/codemp/rd-vanilla/tr_world.cpp
    src/codemp/server/NPCNav/navigator.cpp
    src/codemp/server/sv_bot.cpp
    src/codemp/server/sv_ccmds.cpp
    src/codemp/server/sv_challenge.cpp
    src/codemp/server/sv_client.cpp
    src/codemp/server/sv_game.cpp
    src/codemp/server/sv_gameapi.cpp
    src/codemp/server/sv_init.cpp
    src/codemp/server/sv_main.cpp
    src/codemp/server/sv_net_chan.cpp
    src/codemp/server/sv_snapshot.cpp
    src/codemp/server/sv_world.cpp
)

# Vita platform layer + third-party (carried from JAVITA, same upstream)
set(JAMP_PLATFORM_SOURCES
    src/globals.cpp
    src/lib/minizip/ioapi.c
    src/lib/minizip/unzip.c
    src/shared/qcommon/q_color.c
    src/shared/qcommon/q_math.c
    src/shared/qcommon/q_string.c
    src/shared/qcommon/safe/files.cpp
    src/shared/qcommon/safe/string.cpp
    src/shared/sdl/sdl_input.cpp
    src/shared/sdl/sdl_sound.cpp
    src/shared/sdl/sdl_window.cpp
    src/shared/sys/con_log.cpp
    src/shared/sys/con_tty.cpp
    src/shared/sys/snapvector.cpp
    src/shared/sys/sys_event.cpp
    src/shared/sys/sys_main.cpp
    src/shared/sys/sys_unix.cpp
    src/vita/sys_modules.cpp
)

set(JAMP_GAME_SOURCES
    src/codemp/game/ai_main.c
    src/codemp/game/ai_util.c
    src/codemp/game/ai_wpnav.c
    src/codemp/game/AnimalNPC.c
    src/codemp/game/bg_g2_utils.c
    src/codemp/game/bg_misc.c
    src/codemp/game/bg_panimate.c
    src/codemp/game/bg_pmove.c
    src/codemp/game/bg_saber.c
    src/codemp/game/bg_saberLoad.c
    src/codemp/game/bg_saga.c
    src/codemp/game/bg_slidemove.c
    src/codemp/game/bg_vehicleLoad.c
    src/codemp/game/bg_weapons.c
    src/codemp/game/FighterNPC.c
    src/codemp/game/g_active.c
    src/codemp/game/g_bot.c
    src/codemp/game/g_client.c
    src/codemp/game/g_cmds.c
    src/codemp/game/g_combat.c
    src/codemp/game/g_cvar.c
    src/codemp/game/g_exphysics.c
    src/codemp/game/g_ICARUScb.c
    src/codemp/game/g_items.c
    src/codemp/game/g_log.c
    src/codemp/game/g_main.c
    src/codemp/game/g_mem.c
    src/codemp/game/g_misc.c
    src/codemp/game/g_missile.c
    src/codemp/game/g_mover.c
    src/codemp/game/g_nav.c
    src/codemp/game/g_navnew.c
    src/codemp/game/g_object.c
    src/codemp/game/g_saga.c
    src/codemp/game/g_session.c
    src/codemp/game/g_spawn.c
    src/codemp/game/g_svcmds.c
    src/codemp/game/g_syscalls.c
    src/codemp/game/g_target.c
    src/codemp/game/g_team.c
    src/codemp/game/g_timer.c
    src/codemp/game/g_trigger.c
    src/codemp/game/g_turret.c
    src/codemp/game/g_turret_G2.c
    src/codemp/game/g_utils.c
    src/codemp/game/g_vehicles.c
    src/codemp/game/g_vehicleTurret.c
    src/codemp/game/g_weapon.c
    src/codemp/game/NPC.c
    src/codemp/game/NPC_AI_Atst.c
    src/codemp/game/NPC_AI_Default.c
    src/codemp/game/NPC_AI_Droid.c
    src/codemp/game/NPC_AI_GalakMech.c
    src/codemp/game/NPC_AI_Grenadier.c
    src/codemp/game/NPC_AI_Howler.c
    src/codemp/game/NPC_AI_ImperialProbe.c
    src/codemp/game/NPC_AI_Interrogator.c
    src/codemp/game/NPC_AI_Jedi.c
    src/codemp/game/NPC_AI_Mark1.c
    src/codemp/game/NPC_AI_Mark2.c
    src/codemp/game/NPC_AI_MineMonster.c
    src/codemp/game/NPC_AI_Rancor.c
    src/codemp/game/NPC_AI_Remote.c
    src/codemp/game/NPC_AI_Seeker.c
    src/codemp/game/NPC_AI_Sentry.c
    src/codemp/game/NPC_AI_Sniper.c
    src/codemp/game/NPC_AI_Stormtrooper.c
    src/codemp/game/NPC_AI_Utils.c
    src/codemp/game/NPC_AI_Wampa.c
    src/codemp/game/NPC_behavior.c
    src/codemp/game/NPC_combat.c
    src/codemp/game/NPC_goal.c
    src/codemp/game/NPC_misc.c
    src/codemp/game/NPC_move.c
    src/codemp/game/NPC_reactions.c
    src/codemp/game/NPC_senses.c
    src/codemp/game/NPC_sounds.c
    src/codemp/game/NPC_spawn.c
    src/codemp/game/NPC_stats.c
    src/codemp/game/NPC_utils.c
    src/codemp/game/SpeederNPC.c
    src/codemp/game/tri_coll_test.c
    src/codemp/game/w_force.c
    src/codemp/game/w_saber.c
    src/codemp/game/WalkerNPC.c
    src/codemp/qcommon/q_shared.c
)

set(JAMP_CGAME_SOURCES
    src/codemp/game/AnimalNPC.c
    src/codemp/game/bg_g2_utils.c
    src/codemp/game/bg_misc.c
    src/codemp/game/bg_panimate.c
    src/codemp/game/bg_pmove.c
    src/codemp/game/bg_saber.c
    src/codemp/game/bg_saberLoad.c
    src/codemp/game/bg_saga.c
    src/codemp/game/bg_slidemove.c
    src/codemp/game/bg_vehicleLoad.c
    src/codemp/game/bg_weapons.c
    src/codemp/game/FighterNPC.c
    src/codemp/game/SpeederNPC.c
    src/codemp/game/WalkerNPC.c
    src/codemp/cgame/cg_consolecmds.c
    src/codemp/cgame/cg_cvar.c
    src/codemp/cgame/cg_draw.c
    src/codemp/cgame/cg_drawtools.c
    src/codemp/cgame/cg_effects.c
    src/codemp/cgame/cg_ents.c
    src/codemp/cgame/cg_event.c
    src/codemp/cgame/cg_info.c
    src/codemp/cgame/cg_light.c
    src/codemp/cgame/cg_localents.c
    src/codemp/cgame/cg_main.c
    src/codemp/cgame/cg_marks.c
    src/codemp/cgame/cg_newDraw.c
    src/codemp/cgame/cg_players.c
    src/codemp/cgame/cg_playerstate.c
    src/codemp/cgame/cg_predict.c
    src/codemp/cgame/cg_saga.c
    src/codemp/cgame/cg_scoreboard.c
    src/codemp/cgame/cg_servercmds.c
    src/codemp/cgame/cg_snapshot.c
    src/codemp/cgame/cg_spawn.c
    src/codemp/cgame/cg_syscalls.c
    src/codemp/cgame/cg_turret.c
    src/codemp/cgame/cg_view.c
    src/codemp/cgame/cg_weaponinit.c
    src/codemp/cgame/cg_weapons.c
    src/codemp/cgame/fx_blaster.c
    src/codemp/cgame/fx_bowcaster.c
    src/codemp/cgame/fx_bryarpistol.c
    src/codemp/cgame/fx_demp2.c
    src/codemp/cgame/fx_disruptor.c
    src/codemp/cgame/fx_flechette.c
    src/codemp/cgame/fx_force.c
    src/codemp/cgame/fx_heavyrepeater.c
    src/codemp/cgame/fx_rocketlauncher.c
    src/codemp/qcommon/q_shared.c
    src/codemp/ui/ui_shared.c
)

set(JAMP_UI_SOURCES
    src/codemp/game/bg_misc.c
    src/codemp/game/bg_saberLoad.c
    src/codemp/game/bg_saga.c
    src/codemp/game/bg_vehicleLoad.c
    src/codemp/game/bg_weapons.c
    src/codemp/qcommon/q_shared.c
    src/codemp/ui/ui_atoms.c
    src/codemp/ui/ui_cvar.c
    src/codemp/ui/ui_force.c
    src/codemp/ui/ui_gameinfo.c
    src/codemp/ui/ui_main.c
    src/codemp/ui/ui_saber.c
    src/codemp/ui/ui_shared.c
    src/codemp/ui/ui_syscalls.c
)
